### ISSUE TITLE
Footer: Link to Mozilla page is broken

### ISSUE THREAD

**Issue by niklasmtj** [mozilla-lockbox/mozilla-lockbox.github.io#103]
When clicking on the Mozilla icon in the bottom left of the page one is redirected to https://mozilla-lockbox.github.io/mozilla.org and not https://mozilla.org. The result is a 404 page provided by GitHub pages.

![image](https://user-images.githubusercontent.com/22395665/55008916-08c76800-4fe2-11e9-8c64-53f8e7f181f0.png)

This might be a problem with [this line](https://github.com/mozilla-lockbox/mozilla-lockbox.github.io/blob/13970a6f4b4500ccfcf9f221f93598096aa582d4/_includes/footer.html#L3) and how the `a` tag is handled by Jekyll.

Happens on Windows 10 with Firefox 66 and Chrome 73

**Comment by devinreams** [comment]
Thank you for reporting this @niklasmtj
