### ISSUE TITLE
FAQ - remove link to sign up for Android access

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/mozilla-lockbox.github.io#106]
Currently the "What is Firefox Lockbox?" section still asks users to sign up for Android access. Let's revise that to read:

> Firefox Lockbox is an experimental product from Mozilla, the makers of Firefox. It’s an app for iOS and Android that gives you access to passwords you’ve saved to Firefox.

**Comment by devinreams** [comment]
Closed at #107
