### ISSUE TITLE
Feature (accessibility): Keep focus in left sidebar

### ISSUE THREAD

**Issue by kjcole** [mozilla-lockbox/mozilla-lockbox.github.io#145]
When visiting "about:logins", and clicking on any entry in the left sidebar, the focus is immediately moved to the [Edit] button in the right (main) panel.

Instead, (IMHO), focus should stay in the left sidebar, so that using the cursor keys -- and potentially any other keyboard shortcuts -- will allow easy, mouseless scrolling up and down between different entries.

**Comment by ddurst** [comment]
Since lockwise is now part of Firefox, a better place to report this is bugzilla. That said, this is already reported there as https://bugzilla.mozilla.org/show_bug.cgi?id=1576026 so I'll close this as a duplicate. Thanks for the report!
