### ISSUE TITLE
Publish static .well-known content

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/mozilla-lockbox.github.io#15]
Some features require specific content to be loaded from a path based on `/.well-known/`.  To support these, the directory and its static content needs to be published.

* [ ] iOS Universal Links (mozilla-lockbox/lockbox-ios#17)

**Comment by devinreams** [comment]
@sashei You can use this pull request to add any and all files you need publicly accessible on the web: 
https://github.com/mozilla-lockbox/mozilla-lockbox.github.io/pull/17

Once merged, they'll be live at mozilla-lockbox.github.io 😁
