### ISSUE TITLE
Projects in GitHub link 404s

### ISSUE THREAD

**Issue by pdehaan** [mozilla-lockbox/mozilla-lockbox.github.io#3]
### Steps to reproduce:
1. Go to https://mozilla-lockbox.github.io/
1. Click the "Projects in GitHub" link at the top/right.

### Actual results:
Goes to https://github.com/orgs/mozilla-lockbox/projects, promptly 404s.

Not sure if the correct link should be: https://github.com/mozilla-lockbox/
Or if I get 404s because I'm not a blessed member of the project and can't see the board or something. ¯\\\_(ツ)\_/¯

**Comment by devinreams** [comment]
>Or if I get 404s because I'm not a blessed member of the project 

Yeah, that's it. Thanks for catching that.

Closing this for now as Projects may not remain in our long term process for outside involvement.

Will update (and potentially supersede) this section next week when we formalize our internal design/build processes.
