### ISSUE TITLE
Repos aren't linked on site

### ISSUE THREAD

**Issue by pdehaan** [mozilla-lockbox/mozilla-lockbox.github.io#4]
### Steps to reproduce
1. Go to https://mozilla-lockbox.github.io/

### Actual results
Project repos aren't auto-linked when browsing github.io, but are if you're browsing the https://github.com/mozilla-lockbox/mozilla-lockbox.github.io/blob/master/index.md page directly on GitHub.

**Comment by devinreams** [comment]
Fixed at 2298b4c9b3ba6a3f346be39386900512455c138c
