### ISSUE TITLE
AWS deployment errors

### ISSUE THREAD

**Issue by bqbn** [mozilla-lockbox/mozilla-lockbox.github.io#40]
There are a couple deployment errors after configuring the AWS related environment variables:

* `S3 client configured for "us-east-1" but the bucket "[secure]" is in "us-west-2"; Please configure the proper region to avoid multiple unnecessary redirects and signing attempts` when uploading to s3
* `OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/dateutil'` when running "pip install awscli".

First one is more like a warning, but still worth fixing.

Please see https://travis-ci.org/mozilla-lockbox/mozilla-lockbox.github.io/jobs/358618355 for details.

**Comment by bqbn** [comment]
Also we need to set `acl: public_read` on the s3 provider in order to make the uploaded objects public readable.

**Comment by linuxwolf** [comment]
@bqbn how would you prefer to configure the region?  Via an environment variable like the others, or for us to code it into the `.travis.yml` (or something else)?

As for the error, I do not see the `pip install awscli` failure in any of our travis-ci builds.  Is this your own branch per chance?

**Comment by linuxwolf** [comment]
I see the raw log, and am investigating how to address it.

**Comment by bqbn** [comment]
> how would you prefer to configure the region?

I think env variable is OK. It feels more flexible and is consistent with the others.

**Comment by linuxwolf** [comment]
@bqbn PR #41 is the latest that should address the issues.

The environment variable `AWS_REGION` is used to specify the region.
