### ISSUE TITLE
Product requirements doc

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/mozilla-lockbox.github.io#45]
Requirements definition with

- [x] Problem
- [x] Success criteria
- [x] Metrics
- [x] Hypotheses
- [x] Schedule with Milestones

**Comment by devinreams** [comment]
Drafted schedule with milestones: https://docs.google.com/document/d/1EAjTp6e10RnoWFhFw2zgWjaJXT5KnREz_INb8zxPPtY/edit

(stuff is missing, incomplete, highlighted and needs attention)
