### ISSUE TITLE
Test Pilot Detail Page

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/mozilla-lockbox.github.io#47]
Related to #44 

## Acceptance criteria

- [x] Should have content that outlines the prerequisites / disclaimer for using Lockbox
   - Requires Saved Logins in Fx 
   - Requires Sync Account
- ~Should provide context for login transparency~
- [ ] Should have access to Saved Logins for management
  - chrome://passwordmgr/content/passwordManager.xul  
- [x] Should talk to security language/focus 
   - Needs legal review mozilla-lockbox/lockbox-ios#203
- [x] Should have screenshots / imagery to support the content
- [x] Should include a description of features/functionality/approach
  - see related mozilla-lockbox/lockbox-ios#176 mozilla-lockbox/lockbox-ios#177
- [x] Should have iOS app store link to download
  - https://itunes.apple.com/us/app/firefox-lockbox/id1314000270?ls=1&mt=8

**Comment by nickbrandt** [comment]
@changecourse do you know if there is a Sketch template file available for this once we get into the design?

**Comment by changecourse** [comment]
I don't believe so, but we can reach out to their team via slack to confirm... I also believe that Sevaan is working on UX improvements to TxP mobile

**Comment by devinreams** [comment]
Updated list above with links of items we'll pull together (promo materials, link to app store). ☝️ 

Also noted this is related to #44

**Comment by devinreams** [comment]
In progress here with follow-up todos for launch:
https://github.com/mozilla/testpilot/pull/3624

@mozilla-lockbox/product has the page content been reviewed so this can be "completed"? It sounded like content/copy was going to take another look?

**Comment by devinreams** [comment]
The initial content set up is complete, @sandysage has reviewed it and asked others to.

At this point we can close this issue and rely on the follow-up checklists to go live:

- initial PR to add experiment to testpilot: https://github.com/mozilla/testpilot/pull/3624 ✅ 

- follow-up checklist to go live (so we don't forget anything): https://github.com/mozilla-lockbox/mozilla-lockbox.github.io/issues/44 🕐
