### ISSUE TITLE
Finish Test Pilot featured video

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/mozilla-lockbox.github.io#48]
If want to be a featured experiment, should have a video demo (external resource available)

Related to #44

**Comment by sandysage** [comment]
@changecourse I believe this is close to complete with feedback/revisions provided 6/15. Do you have an idea of when we'll get this 'final' asset uploaded to Firefox YouTube channel and displayed on Test Pilot?

**Comment by changecourse** [comment]
@sandysage I'll be receiving a revised draft tomorrow, which should account for the majority of feedback. Pending the completion of changes, when is the absolute required date for this to be completed by?

**Comment by devinreams** [comment]
Final video received and URL added to Test Pilot [PR](https://github.com/mozilla/testpilot/pull/3624). 📹 ✅💥
