### ISSUE TITLE
Add privacy policy content to website

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/mozilla-lockbox.github.io#57]
at privacy.html

**Comment by sandysage** [comment]
@devinreams We have a privacy policy written here: https://docs.google.com/document/d/1O5Y0es540JZouCN7LcXYO40L5LbS2QlLLkGDsXBwHc4/edit#heading=h.daaezhyzwo9

I'm happy to create the file and get this in place. But I don't want to proceed without checking with you first (step on toes, get in right place, etc.). If you don't mind, please let me know how and where I can be most helpful to you.

**Comment by devinreams** [comment]
> If you don't mind, please let me know how and where I can be most helpful to you.

Check out #65 and make sure it looks how you want/expect. With your approval we'll be all set 💃
