### ISSUE TITLE
Final updates to marketing assets

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/mozilla-lockbox.github.io#66]
Reminder to triple check before we go live:

- [x] App Store assets (approval from Marketing)
  - including updated screenshots
- [x] [Test Pilot page](https://github.com/mozilla-lockbox/mozilla-lockbox.github.io/issues/44) (approvals from Test Pilot, Legal, Copy)
  - [x] Twitter social card image
  - [x] Facebook social card image

Twitter and Facebook share images attached:
[share-images.zip](https://github.com/mozilla-lockbox/mozilla-lockbox.github.io/files/2129108/share-images.zip)

**Comment by devinreams** [comment]
Waiting on final changes from Invision design and content so I can get them in at https://github.com/mozilla/testpilot/pull/3624

**Comment by changecourse** [comment]
Updated content shown here:
https://mozilla.invisionapp.com/share/WMGTZLLEYCA#/291012374_Detail_Page 

Let me know if you'd like me to provide it in a better way for updating on our PR @devinreams

**Comment by devinreams** [comment]
PR updated 💥 

Last two items are in https://github.com/mozilla-lockbox/mozilla-lockbox.github.io/issues/44 (video and "Your privacy" section)

**Comment by devinreams** [comment]
![screenshot_2018-06-26 firefox test pilot](https://user-images.githubusercontent.com/49511/41930568-a470410e-7938-11e8-8f27-df822fdc581c.png)

From https://github.com/mozilla/testpilot/pull/3624
