### ISSUE TITLE
Update FAQ content to be a little more clear in some instructions

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockbox/mozilla-lockbox.github.io#68]
This updates a couple of the sections of the FAQ to be a little more clear as well as adds in images to aid the user. One of these changes includes an update to an FAQ question title, which will result in a need to update a link in the iOS app.

### Proposed Changes (feel free to comment in InVision with thoughts)
https://mozilla.invisionapp.com/share/CNLJJ6OE9Y7#/304380300_FAQ_Updates

Current Site:
https://lockbox.firefox.com/faq.html
https://github.com/mozilla-lockbox/mozilla-lockbox.github.io/blob/master/faq.md

- [x] Update "How do I use Firefox Lockbox?" question title.
- [x] Update "How do I enable sync on Firefox?" for On Desktop answer content
- [x] Update "How do I enable sync on Firefox?" for On iOS answer content
- [x] Add in images to aid in instructions
- [x] Update any CSS that needs adjusted with changes
- [ ] Update FAQ link in iOS App

**Comment by devinreams** [comment]
@nickbrandt I assume the flow from here is make sure @sandysage and related product folks are good with the changes _then_ we (you, eng) can help get the changes in place, right?

In other words: I'll hold off helping here until someone says we're good to go 👍

**Comment by nickbrandt** [comment]
@devinreams Yep exactly. If you have any thoughts about the updates or inclusion of images let me know!

**Comment by changecourse** [comment]
@sandysage pending your 👍 we'll begin implementation.

**Comment by sandysage** [comment]
Just reviewed. Looks good on my end.

The images really help with the content. Can we make these updates first so we can confirm the added content works well in our mobile webview? We are assuming users will be navigating the FAQs primarily from our app.

The question title change works for me. Is there any way to confirm this is the last the changes here for awhile (required code changes)? Are there any other reviews that need to happen (eg content, test pilot) that need consideration before calling this 'done'? I'd like to avoid adding scope for one-off changes, and better consolidate these where we can.

**Comment by devinreams** [comment]
>Is there any way to confirm this is the last the changes here for awhile (required code changes)?

When we make the changes to the website I will hard-code anchor tags/names that can remain the same forever (no matter if the title itself changes) and will jump the user to the same spot.

**Comment by changecourse** [comment]
@devinreams sounds great! 

After discussion we feel confident that we can proceed forward with these changes.
