### ISSUE TITLE
Move rework.html to Index

### ISSUE THREAD

**Issue by johngruen** [mozilla-lockbox/mozilla-lockbox.github.io#98]
When the Android App goes live we should take `rework.md` and change it to `index.md` when this happens we'll need to do the following

- [x] add GPS and App Store links to `_config.yml`
- [x] swap the `index.md` file
- [x] Make sure the right links are showing up in the footer and header navs also in `_config.yml`
- coordinate the FAQ merge at the same time at #93

**Comment by johngruen** [comment]
(once #96 gets merged)

**Comment by devinreams** [comment]
I went ahead and updated the app store links and checked it off above 🔗 ✅

**Comment by devinreams** [comment]
Started a branch to get these changes in: #99

I think that covers everything!
